version: '3'

services:
  rdb:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - posgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=bookshelf-user
      - POSTGRES_DB=bookshelf
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
  redis:
    image: redis:7
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis/data
    # environment:
    #   - REDIS_USER=bookshelf-user
    #   - REDIS_PASS=password
    #   - REDIS_HOST=localhost
    #   - REDIS_PORT=6379
volumes:
  posgres:
  redis: